apiVersion: v2
name: "cray-hms-hbtd"
version: 3.2.2-test
description: "Kubernetes resources for cray-hms-hbtd"
home: "https://github.com/Cray-HPE/hms-hbtd-charts"
sources:
  - "https://github.com/Cray-HPE/hms-hmi-service"
dependencies:
  - name: cray-service
    version: "~12.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
  - name: cray-etcd-base
    version: "1.3.0-20250424175301+e8d1e5b"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: "1.23.0"  # update pprof image version below as well
annotations:
  artifacthub.io/images: |-
    - name: cray-hbtd-pprof
      image: artifactory.algol60.net/csm-docker/stable/cray-hbtd-pprof:1.23.0
  artifacthub.io/license: "MIT"
