apiVersion: v2
name: "cray-hms-hbtd"
version: 2.1.1
description: "Kubernetes resources for cray-hms-hbtd"
home: "https://github.com/Cray-HPE/hms-hbtd-charts"
sources:
  - "https://github.com/Cray-HPE/hms-hmi-service"
dependencies:
  - name: cray-service
    version: "~7.0.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: "1.16.0"
annotations:
  artifacthub.io/license: "MIT"
